// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokrocile_programovaci_prostredky.Api.Data;

#nullable disable

namespace Pokrocile_programovaci_prostredky.Api.Migrations
{
    [DbContext(typeof(NemocniceDbContext))]
    [Migration("20220426145821_nove data2")]
    partial class novedata2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("Pokrocile_programovaci_prostredky.Api.Data.RevizeData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VybaveniDataID")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VybaveniDataID");

                    b.ToTable("Revizes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b21ec945-0b43-42b7-b900-900a95b1556b"),
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            VybaveniDataID = new Guid("4d2fb71e-658a-4cda-b279-88ad33d6057a")
                        },
                        new
                        {
                            Id = new Guid("1754100a-54e7-4f14-a6aa-e23e09629ec1"),
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            VybaveniDataID = new Guid("bc541f54-965f-45b2-a18b-aacf68e81c37")
                        },
                        new
                        {
                            Id = new Guid("c1287015-5d0c-4d87-bc3c-2170d64f1538"),
                            DateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "",
                            VybaveniDataID = new Guid("555242cb-c93a-4f71-9350-eeb58c681e13")
                        });
                });

            modelBuilder.Entity("Pokrocile_programovaci_prostredky.Api.Data.VybaveniData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BoughtDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PriceCzk")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Vybavenis");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4d2fb71e-658a-4cda-b279-88ad33d6057a"),
                            BoughtDateTime = new DateTime(2020, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "XXX",
                            PriceCzk = 500.0
                        },
                        new
                        {
                            Id = new Guid("bc541f54-965f-45b2-a18b-aacf68e81c37"),
                            BoughtDateTime = new DateTime(2018, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ZZZZ",
                            PriceCzk = 100.0
                        },
                        new
                        {
                            Id = new Guid("555242cb-c93a-4f71-9350-eeb58c681e13"),
                            BoughtDateTime = new DateTime(2017, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "yyyyy",
                            PriceCzk = 20.0
                        });
                });

            modelBuilder.Entity("Pokrocile_programovaci_prostredky.Api.Data.RevizeData", b =>
                {
                    b.HasOne("Pokrocile_programovaci_prostredky.Api.Data.VybaveniData", "Vybaveni")
                        .WithMany("Revizions")
                        .HasForeignKey("VybaveniDataID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vybaveni");
                });

            modelBuilder.Entity("Pokrocile_programovaci_prostredky.Api.Data.VybaveniData", b =>
                {
                    b.Navigation("Revizions");
                });
#pragma warning restore 612, 618
        }
    }
}
